#!/bin/sh
########################################################################
# Begin seatd
#
# Description : seatd init script
#
# Author      : Vuong Le - lelordoftech@gmail.com
#
# Version     : BLFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            seatd
# Required-Start:      $local_fs $network
# Should-Start:        networkmanager wicd
# Required-Stop:       $local_fs $network
# Should-Stop:         networkmanager wicd
# Default-Start:       5
# Default-Stop:        0 1 6
# Short-Description:   Starts seatd.
# Description:         Starts seatd daemon.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

BIN_FILE="/usr/bin/seatd"

case "$1" in
   start)
      log_info_msg "Starting seatd..."
      start_daemon ${BIN_FILE} -g seat &
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping seatd..."
      killproc ${BIN_FILE}
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc ${BIN_FILE}
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End /etc/init.d/seatd
