#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Windows Boot Manager (on /dev/sdb1)' {
	insmod part_gpt
	insmod fat
	set root='hd1,gpt1'
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}

menuentry "Reboot" {
  reboot
}

menuentry "Shut Down" {
  halt
}